export default {
  ARGUMENT_ERROR: 'ARGUMENT_ERROR',

  MOUSE_DOWN: 'MOUSE_DOWN',
  MOUSE_UP: 'MOUSE_UP',
  MOUSE_MOVE: 'MOUSE_MOVE',
  MOUSE_DRAG: 'MOUSE_DRAG',
  MOUSE_DROP: 'MOUSE_DROP',
  MOUSE_HOVER: 'MOUSE_HOVER',

  SPRITE_TYPE_TEXT: 'TEXT',
  SPRITE_TYPE_PATH: 'PATH',
  SPRITE_TYPE_IMAGE: 'IMAGE',
  SPRITE_TYPE_RECT: 'RECT',
  SPRITE_TYPE_POLYGON: 'POLYGON',
  SPRITE_TYPE_CIRCLE: 'CIRCLE',
  SPRITE_TYPE_ELLIPSE: 'ELLIPSE',
  SPRITE_TYPE_LINE: 'LINE',
};