export default {
  ARGUMENT_ERROR: 'ARGUMENT_ERROR',

  MOUSE_DOWN: 'MOUSE_DOWN',
  MOUSE_UP: 'MOUSE_UP',
  MOUSE_MOVE: 'MOUSE_MOVE',
  MOUSE_DRAG: 'MOUSE_DRAG',
  MOUSE_DROP: 'MOUSE_DROP',
  MOUSE_HOVER: 'MOUSE_HOVER',
};